### ISSUE TITLE
Can we get this to work with 2.11 and maybe 2.12?

### ISSUE THREAD

**Issue by i-am-the-slime** [orrsella/sbt-sound#4]
How hard would this be?

**Comment by i-am-the-slime** [comment]
@orrsella I'd really still love this.

**Comment by orrsella** [comment]
Hey, I haven't been working with Scala for the past, so didn't get a chance to look into this. Can you please give some details into what doesn't work? Which versions of SBT/Scala/the plugin you're using and what you're seeing?

Also, if you want to take a jab at fixing this I'd love to do the code review :)

**Comment by orrsella** [comment]
@i-am-the-slime please try version `addSbtPlugin("com.orrsella" % "sbt-sound" % "1.0.6")` for 2.12.
